<div class="w-25 mx-auto pt-5" >
    
    <form action="do-password-update.php" method="post">
       <div class="form-group" >
        <label for="Password">Nouveau mot de passe :</label>
            <input type="text" name="password" value="" size="30" placeholder="password" required id="passwordx" class="form-control">
        </div>
        <div class="form-group">
        <label for="password">Confirmer nouveau mot de passe :</label>
            <input type="text" name="passwordx" value="" size="30" placeholder="password" required id="passwordx" class="form-control">
        </div>
        <input type="submit" name="submit" value="Modifier" class="btn btn-warning">
         <input type="hidden" name="hidden" value="<?=$identification?>">
  </form>
</div>