<div class="w-25 mx-auto pt-4" >
   
    <form action="do-post-update.php" method="post" enctype="multipart/form-data">
    <div class="form-group">
    <label for="title">Title :</label>

        <input type="text" name="title"  size="30" placeholder="title" value="<?=$object->getTitle()?>" required id="titre" class="form-control">
    </div>
  
    <div class="form-group">
    <label for="content">Content :</label>
        <textarea id="" cols="40" rows="12"  name="content" placeholder="write here" required id="content" class="form-control" ><?=$object->getContent()?></textarea>
    </div>
    <div class="form-group">
    <label for="file">file :</label>
  <!-- <p>Le fichier ne doit pas etre de tres gros taille(environ 30KO maximum) et doit etre au format jpeg</p>   -->
        <input type="file" name="photo" value=""  placeholder=""  required accept="image/jpeg, image/jpg" id="file" class="form-control-file border">
    </div>
    <br>
    <input type="submit" name="submit" value="Modifier" class="btn btn-warning">
    <input type="hidden" name="hidden" value="<?=$Id?>">
    </form>
</div>