<div class="w-25 mx-auto pt-5" >
<form action="do-sign-in.php" method="post">
<div class="form-group">
    <label for="username">Nom d'utilisateur :</label>
    <input type="text" name="username" value="" size="30" placeholder="@pseudo" required class="form-control" id="username">
</div>
<div>
    <br>
</div>
<div class="form-group">
<label for="password">Mot de passe :</label>

    <input type="password" name="password" value="" size="30" placeholder="password" required class="form-control" id="password">
</div>
<div>
    <br>
</div>
<input type="submit" name="submit" value="Connexion" class="btn btn-primary">
</form>
<a href="sign-up.php" class="btn btn-success" role="button">Créer un compte</a></p>
</div>
