<div class="w-25 mx-auto pt-2" >
    <form action="do-sign-up.php" method="post">
        <div class="form-group">
            <label for="username">Nom d'utilisateur :</label>
            <input type="text" name="username" value="" size="30" placeholder="@pseudo" required class="form-control" id="username">
        </div>
  
    <div class="form-group">
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" value="" size="30" placeholder="password" required id="password" class="form-control">
    </div>
    <div class="form-group">
        <label for="passwordx">Repeter mot de passe :</label>
        <input type="password" name="passwordx" value="" size="30" placeholder="password" required id="passwordx" class="form-control">
    </div>

    <div class="form-group" >
    <label for="prenom">Prenom :</label>
        <input type="text" name="firstname" value="" size="30" placeholder="firstname" required id="prenom" class="form-control">
    </div>
 
    <div class="form-group">
    <label for="nom">Nom de famille :</label>
        <input type="text" name="lastname" value="" size="30" placeholder="name" required id="nom" class="form-control">
    </div>

    <div class="form-group">
    <label for="email">Email :</label>
        <input type="email" name="email" value="" size="30" placeholder="@" required id="email" class="form-control">
    </div>
    <input type="submit" name="submit" value="Créer" class="btn btn-primary">
    </form>
</div>