<div class="w-25 mx-auto pt-5" >
    
    <form action="do-user-update.php" method="post">
         <div class="form-group">
            <label for="username">Nom d'utilisateur :</label>
            <input type="text" name="username" value="<?=$object->getUsername()?>" size="30" placeholder="@pseudo" required class="form-control" id="username">
        </div>
        <div class="form-group" >
        <label for="prenom">Prenom :</label>
            <input type="text" name="firstname" value="<?=$object->getFirstname()?>" size="30" placeholder="firstname" required id="prenom" class="form-control">
        </div>
        <div class="form-group">
        <label for="nom">Nom de famille :</label>
            <input type="text" name="lastname" value="<?=$object->getLastname()?>" size="30" placeholder="name" required id="nom" class="form-control">
        </div>
        <div class="form-group">
        <label for="email">Email :</label>
            <input type="email" name="email" value="<?=$object->getEmail()?>" size="30" placeholder="@" required id="email" class="form-control">
        </div>
        <input type="submit" name="submit" value="Modifier" class="btn btn-warning">
         <input type="hidden" name="hidden" value="<?=$identification?>">
      </form>
    </div>