<div>
    <a href="list.php" class="btn btn-info" role="button"><< Retour</a>
</div>
<div class="row">
<div class="col">

<h5>Title  </h5> <?=$post->getTitle()?>
<h5>Username and Date  </h5> <?=$post->getUsername()?> - <?=date("d/m/Y",$post->getDateTime())?>
        
<h5>Content  </h5><?=$post->getContent()?></div>
<div class="col">
<?='<img src="data:image/jpg;base64,' .$post->getPhoto() . '" />'?> 
</div>
</div>

<hr>
<?php if (isOwner($post)) { ?>
    <div class="row justify-content-center">
        <div class="col">
    </div>

        <div class="col">

             <a href="post-update.php?<?=$post->getID()?>" class="btn btn-primary" role="button">[Modifier]</a>
        </div>
        <div class="col"><a href="#demo" class="btn btn-warning" role="button" data-toggle="collapse">[Supprimer]</a></div>
            <div id="demo" class="collapse">
        <a href="list.php" class="btn btn-success" role="button">ANNULER</a>
        <a href="do-post-delete.php?<?=$post->getID()?>" class="btn btn-danger" role="button">CONFIRMER</a>
        <div class="col">
        </div>
    
    </div>


    </div>
<?php } ?>
